apiVersion: v1
kind: Service
metadata:
  name: demo-svc
  namespace: default
spec:
  type: NodePort
  selector:
    app: demo
  ports:
  - nodePort: 30888 # host's port
    port: 8888      # service's port
    targetPort: 8080  # target pod's port